# Generated by Django 5.2.14 on 2026-06-09 06:37

import dojo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0268_release_authorization_to_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='company_logo',
            field=models.FileField(blank=True, null=True, upload_to=dojo.models.UniqueUploadNameProvider('company_logo'), verbose_name='Company Logo'),
        ),
        migrations.AddField(
            model_name='system_settings',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Company Name'),
        ),
    ]
